### ISSUE TITLE
Localize the Storyboard

### ISSUE THREAD

**Issue by avielg** [hasadna/Anyway-iOS#3]
Main storyboard has localizaed versions of "base" (currently hebrew, should be english) and "hebrew".
We should translate any text in there to english in `Main.strings (English)`

**Comment by djwbrown** [comment]
Work in progress on localizing the storyboard and UI layout, starting with the Accident Detail View Controller. Feel free to assign me to this issue and check out the changes on the branch below. I'll make a pull request when this View Controller is complete. Thanks!

[https://github.com/djwbrown/Anyway-iOS/tree/djwbrown-localize]

**Comment by djwbrown** [comment]
Noticed that the buttonSource title wasn't changing to English in that localization. Localizing the strings in Constants.swift should fix the issue.

https://github.com/hasadna/Anyway-iOS/blob/master/Anyway/DetailCells.swift#L54

**Comment by avielg** [comment]
I believe it's this part:
https://github.com/hasadna/Anyway-iOS/blob/master/Anyway/Constants.swift#L102

**Comment by avielg** [comment]
@djwbrown after merging, the main issue I saw was in the detail screen. My iPhone is english:
![img_3154](https://cloud.githubusercontent.com/assets/5012557/12111421/dea97092-b39d-11e5-8cc2-6f7aab7731df.PNG)

**Comment by djwbrown** [comment]
Oh, wow. I didn't get this when testing in English on my iPhone 5s. I will try it in the simulator as well and see if I can reproduce it.

**Comment by djwbrown** [comment]
It was just an oversight on the leading-edge/trailing-edge constraints to the icon and label in each table cell. It happened to work perfectly on the 5s width, but not any other width. I removed those constraints and added one to between the leading edge of the icon and the container-margin.
