### ISSUE TITLE
iPad split view bug

### ISSUE THREAD

**Issue by avielg** [hasadna/Anyway-iOS#6]
1. Open the app (when the right "detail" view is empty with the "anyway" logo)
2. Tap a pin in the map and tap the "bubble" to see the accident details
3. There is a "Close" button (in hebrew it shows "סגור" - on the top with blue fram)
   It belongs to the iPhone only - on iPad it doesn't make sense to "close" it.... The button should simply be hidden (and the table should be aligned to the top...).

When fixing this make sure you don't mess up with the iPhone version (:

**Comment by djwbrown** [comment]
Please see PR #13. Thanks!

**Comment by djwbrown** [comment]
It may be nice to return to the default Anyway logo after tapping on the map to dismiss the accident details. The detail view controller should probably cross-fade out at the same time as the marker annotation disappears.
